### PR TITLE
Adding several domains for Department of Education

### PR DESCRIPTION
**Pull request by jsf9k**
NCATS received a big list of domains to add for Department of Education.

### CODE REVIEW

**Comment by jsf9k** [comment]
Good catch, @h-m-f-t!

**Comment by jsf9k** [comment]
Any movement on this one, @h-m-f-t?

**Comment by h-m-f-t** [comment]
@jsf9k I'll kickoff a pshtt scan of these domains and will analyze the results. At worst, we can merge the .gov domains without too much trouble.

I'll aim to clear this from my queue this week.

**Comment by h-m-f-t** [comment]
I did a few things to arrive at this list.

* ran a [pshtt](https://github.com/dhs-ncats/pshtt) scan on all the ED additions, which gave me redirect and other info
* removed second-level .gov domains we already scan for
* browsed to the remaining hostnames (or interacted with them via other tools)
* looked for signs the host was owned by ED (and didn't belong to a non-ED owned SaaS):
  * had a "WARNING Government system" banner
  * served a [DAP](https://github.com/digital-analytics-program/gov-wide-code) file
  * sole purpose appears to be to redirect to a ED .gov system

The raw analysis is [here](https://docs.google.com/spreadsheets/d/1NR4ocSo4Tu_KAvbK0gcqv32IcrXe1z2a0yEwB0Yl3t8/edit?usp=sharing). I did this quickly; there may errors here but I'm comfortable enough with this moving forward.

cc: @tdlowden, there may be interest to ensuring 
* those non-.gov ED sites that are serving DAP get represented on ED's analytics.usa.gov page (mostly the grads360.org sites)
* those ED sites that we're adding that don't serve DAP that should be do so (if the `DAP?` value is empty, I didn't evaluate.)

**Comment by jsf9k** [comment]
This looks fine to me, @h-m-f-t.

**Pull request merged**
