### PR TITLE
Adding sites from BOD 18-01 preload submissions

### PR DESCRIPTION
**Pull request by h-m-f-t**
Agencies have shared 18-01 preload submissions, some of which are not represented here.

### CODE REVIEW

**Comment by currencyInvestments** [comment]
Fine

**Comment by konklone** [comment]
@h-m-f-t I resolved conflicts to bring this up to date. I also removed the second row from each one, since this CSV doesn't have an agency row (which I understand is an issue where there are `.com` and `.org` domains). 

I'm up for expanding this to have an optional Agency row, but wanted to do that explicitly, in a separate PR, rather than have some rows' columns mismatch the header rows' columns.

Other thought: I wonder if GSA/DotGov should publish a list of non-`.gov` parent domains that are owned/registered by agencies?

cc @jsf9k

**Comment by h-m-f-t** [comment]
@konklone I submitted part of such a list last year at [GSA/govt-urls](https://github.com/GSA/govt-urls/issues/12). OMB's [M-17-06](https://policy.cio.gov/web-policy/domain/) contemplates that list being the canonical one, but I'm supportive of a list existing and being maintained, wherever that is.

**Comment by konklone** [comment]
That repo could reference another DotGov-run location, or the DotGov program could take over govt-urls if it's not otherwise being maintained.

**Comment by dawnpm** [comment]
@konklone In addition to reporting the scope of the government web, the govt-urls list supports the search at USA.gov, for its whole-government scope. We have plans to add an agency affiliation to that taxonomy, though we've not been able to commit the time to assigning that metadata. We may have resources in the coming months, but does the @GSA/dotgov team have the resources for this work? This work used to be staffed from the Search team, and also via Open Opportunity projects. Regardless of who does the work, the Search team *definitely* wants to stay involved.

There are two elements to maintaining the list - adding new sites as federal agencies report them, as @h-m-f-t did, and also updating records, some of which could potentially be automated, depending on the type of update, if we were to move the management of the taxonomy to a different tool (I've got several ideas there). 
* add metadata where needed (not automatable)
* detect 301 redirects and replace with new domain (seems automatable)
* detect 404s and flag for human intervention to discover replacement domain, if any (half automatable)

And then there's the need to discover and add new domains. In theory, federal agencies will report any new domains. Non-fed agencies are not subject to that requirement. This doesn't seem automatable to me, but I'm certainly open to ideas.

**Comment by dawnpm** [comment]
Noting the three domains that were added in this commit, we had the first two, and the third is just a redirect to usmint.gov, so we'll add it but with a pointer to the preferred term.

**Pull request merged**
